post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgdXNlciIsImlkIjoiNWRjMjE1OWE5YzM4ZDIxYzc4MDBmZGM2IiwiaWF0IjoxNTczMDAxNzAwfQ.kKTyVt-BuCpkgKkpkYiPqp5m4DUfQOTzaCZjfLgD9PA

{
  "title": "for testing",
  "author": "Some Authorqwerty",
  "url": "/url/url.com"
}